import { Geist } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.className} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <main>
          <Navbar></Navbar>
          {children}
        </main>
      </body>
    </html>
  );
}
